name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run validations
        run: pnpm validate

  release:
    needs: [validate]
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build-arg: --win
          - os: macos-latest
            build-arg: --mac
          - os: ubuntu-latest
            build-arg: --linux

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Upload artifacts
        run: pnpm exec electron-builder ${{ matrix.build-arg }} --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
